# -*- coding: utf-8 -*-
"""Honeypot_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAwbiM7DMc3xzvwvDS_UEwJfC0A51k1b

## **Honeypot Data Cleaning Pipeline**
*Programmer: Caitlyn Boyd*

*Last Modified: 06/30/2025*

**Description:** This program is intended to clean 24 hours of data from T-pot that is pulled from elastic pot and converted into a .csv file. Future modifications will allow for batch processing of jsonl data taken from the same location.
"""

import pandas as pd
import polars as pl
import ipaddress
import numpy as np


def flatten_nested_columns(df: pd.DataFrame) -> pd.DataFrame:
  for col in df.columns:
    if df[col].apply(lambda x: isinstance(x, list)).any():
      df[col] = df[col].apply(
          lambda x: ', '.join(map(str, x)) if isinstance(x, list) else x
      )
    return df

'''
  Function: drop_constant_columns
  Description: drops all columns that contain only one unique value

  Input:
    - df: pandas dataframe
  Output:
    - pandas dataframe with all constant columns dropped
'''
def drop_constant_columns(df):
  # Identify columns that do NOT contain lists
  non_list_columns = df.columns[~df.applymap(type).eq(list).any()]

  # Keep only those columns temporarily to check for constant values
  df_constants_check = df[non_list_columns]

  # Drop constant columns from the original DataFrame
  constant_columns = df_constants_check.columns[df_constants_check.nunique(dropna=False) <= 1]
  df = df.drop(columns=constant_columns)
  df = df.drop(columns=['timestamp'])
  return df

'''
  Function: print_progress

  Description: Prints the size of the original and cleaned dataframes

  Input:
    - last_l: size of original dataframe
    - last_w: width of original dataframe
    - cur_l: size of cleaned dataframe
    - cur_w: width of cleaned dataframe
  Output:
    - Prints the size of the original and cleaned dataframes
'''
def print_progress(last_l, last_w, cur_l, cur_w):
    print("Original Size:", last_l, "entries", last_w, "columns")
    print("Final Size:", cur_l, "entries", cur_w, "columns")

'''
  Function: drop_local_traffic
  Description: drops all local traffic from the data collected from T-pot using
  Elastic. Drops all entries with the destination 64297 (internal communication
  port), geoip location in Poulsbo (the site of the honeypots), and all error
  alerts from Suricata found through the "tags" column.

  Input:
    - df: pandas dataframe
  Output:
    - df: Pandas dataframe with all local traffic dropped.
'''
def drop_local_traffic(df):
    # Drop rows where dest_port == 64297
    if "dest_port" in df.columns:
        df = df[df["dest_port"] != 64297]

    # Drop rows where geoip.city_name == "Poulsbo"
    if "geoip.city_name" in df.columns:
        df = df[df["geoip.city_name"] != "Poulsbo"]

    # Drop rows where 'tags' is not null (i.e., keep only null/empty tags)
    if "tags" in df.columns:
        df = df[df["tags"].isnull()]

    return df

'''
  Function: remove_suricata_duplicates
  Description: fnds and removes all suricata alerts and appends them to the
  original alert row by "flow_id". Assumes that the data does not cross the 4am
  mark --- which is when suricata resets its flow_ids.

  Input:
    - df: pandas dataframe
  Output:
    - pandas dataframe with all suricata alerts appended to the original alert
      row.
'''
def remove_suricata_duplicates(df):
    filter_col = 'anomaly.event'

    # If the column doesn't exist, return the DataFrame as-is
    if filter_col not in df.columns:
        return df

    # Split into duplicates and clean rows
    duplicates = df[df[filter_col].notnull()]
    clean_df = df[df[filter_col].isnull()]

    # Select only useful columns
    duplicates = duplicates[[
        "flow_id",
        "anomaly.type",
        "anomaly.event",
        "anomaly.layer",
    ]]

    print(duplicates.columns)

    # Aggregate by flow_id, combining unique values
    aggregated = duplicates.groupby("flow_id").agg({
        "anomaly.type": lambda x: ', '.join(pd.unique(x.dropna().astype(str))),
        "anomaly.event": lambda x: ', '.join(pd.unique(x.dropna().astype(str))),
        "anomaly.layer": lambda x: ', '.join(pd.unique(x.dropna().astype(str))),
    }).reset_index()

    # Join the aggregated anomalies back to the clean data
    cleaned_df = clean_df.merge(aggregated, on="flow_id", how="left")

    return cleaned_df

'''
Function: remove_cowrie_duplicates
Description: finds and removes all cowrie events and appends them to the
original alert row by matching the session code. This limits cowrie entries
to one alert per session. Events are identified in the "eventid" column with
values of 'connect', 'end', etc. Session IDs are found int he "session" column.

Appends "message" and "ip_rep" columns to the original alert row.

Input:
    - df: Pandas dataframe
Output:
    - Pandas dataframe with all Cowrie sessions appended to the original alert
      row.
'''
def remove_cowrie_duplicates(df):
    # Step 1: Filter Cowrie duplicates
    duplicates = df[df["type"] == "Cowrie"].copy()
    clean_df = df[df["type"] != "Cowrie"].copy()

    # Step 2: Keep only useful columns
    duplicates = duplicates[[
        "eventid",
        "session",
        "message",
        "ip_rep",
    ]]

    # Step 3: Aggregate entries by session
    aggregated = (
        duplicates
        .groupby("session")
        .agg({
            "eventid": lambda x: ' , '.join(pd.unique(x.dropna().astype(str))),
            "message": lambda x: ' , '.join(pd.unique(x.dropna().astype(str))),
            "ip_rep": lambda x: ' , '.join(pd.unique(x.dropna().astype(str))),
        })
        .reset_index()
    )

    # Step 4: Join the aggregated info back into the cleaned DataFrame
    cleaned_df = clean_df.merge(aggregated, on="session", how="left")

    return cleaned_df

'''
  Function: remove_P0f_duplicates
  Description: identifies all P0f entries by the "type" column and combines them
  to corresponding entries by "src_ip", "@timestamp", "dest_port", "src_port".
  Appends "params", "raw_sig", "os", and "link" columns to the original alert row.

  Input:
    - df: Pandas dataframe
  Output:
    - Pandas dataframe with all P0f entries combined to corresponding entries.
'''
def remove_P0f_duplicates(df):
    # Step 1: Separate P0f and non-P0f entries
    print(df['type'].unique().tolist())
    duplicates = df[df["type"] == "P0f"].copy()
    clean_df = df[df["type"] != "P0f"].copy()
    print(clean_df.shape[0])

    # Step 2: Aggregate P0f entries by key columns
    key_cols = ["src_ip", "dest_ip", "@timestamp", "dest_port", "src_port"]
    agg_cols = ["params", "raw_sig", "os", "link"]

    aggregated = (
        duplicates
        .groupby(key_cols)
        .agg({
            col: lambda x: ' | '.join(pd.unique(x.dropna().astype(str))) for col in agg_cols
        })
        .reset_index()
    )


    # Step 3: Left join aggregated values into clean data
    cleaned_df = clean_df.merge(aggregated, on=key_cols, how="left")

    # Step 4: Find unmatched entries in aggregated
    matched_keys = clean_df[key_cols].drop_duplicates()
    merged_keys = pd.merge(aggregated, matched_keys, on=key_cols, how='left', indicator=True)
    unmatched = merged_keys[merged_keys['_merge'] == 'left_only'].drop(columns=['_merge'])

    # Step 5: Add missing columns to unmatched to match clean_df
    for col in cleaned_df.columns:
        if col not in unmatched.columns:
            unmatched[col] = np.nan

    # Reorder unmatched columns to match
    unmatched = unmatched[cleaned_df.columns]

    # Step 6: Combine clean_df and unmatched aggregated rows
    final_df = pd.concat([cleaned_df, unmatched], ignore_index=True)

    return final_df

'''
  Function: drop_sparse_columns
  Description: drops all columns with less than min_coverage (decimal) entries.

  Input:
    - df: Pandas dataframe
    - min_coverage: decimal value between 0 and 1 representing the minimum
      percentage of data coverage.
  Output:
    - Pandas dataframe with all columns with less than min_coverage entries
      dropped.
'''

def drop_sparse_columns(df, min_coverage):
    always_keep = ['geoip.as_org']

    row_count = len(df)

    # Determine which columns meet the coverage threshold
    columns_to_keep = [
        col for col in df.columns
        if df[col].notnull().sum() >= row_count * min_coverage or col in always_keep
    ]

    return df[columns_to_keep]

'''
  Function: is_private_ip
  Description: decides and returns if an ip address is private.

  Input:
    - ip_str: string representing an ip address
  Output:
    - boolean representing if the ip address is private.
'''
def is_private_ip(ip_str):
    try:
        return ipaddress.ip_address(ip_str).is_private
    except ValueError:
        return False

'''
    Function: id_honeypot
    Description: labels a honeypot according to port number.
    
    Input:
        - df: a pandas dataframe of data
        - honeypot_name: the name of the honeypot
        - port_list: a list of ports associated with the honeypot.
    Output:
        - the dataframe with the honeypot labeled correctly.
'''
def id_honeypot(df, honeypot_name, port_list):
  target_types = ["P0f", "Suricata", "Fatt"]
  target_ports = port_list

  # Identify the rows to modify
  mask = ((df["dest_port"].isin(target_ports)))

  mask2 =  ((df["src_port"].isin(target_ports)) &
            ((df["src_ip"] == "172.200.200.5") | (df["src_ip"] == "127.0.0.1")) &
            ~((is_private_ip(df["dest_port"]))))
  # Modify the "type" where the mask is True
  df.loc[mask, "type"] = honeypot_name
  df.loc[mask2, "type"] = honeypot_name
  print(honeypot_name, "entries found", df[df['type'] == honeypot_name].shape[0])
  return df

'''
  Function: label_hidden_honeypots
  Description: Finds all unlabeled honeypots by port number and labels them
  through the 'type' column.

  Input:
    - df: Pandas dataframe
  Output:
    - Pandas dataframe with all unlabeled honeypots labeled.
'''
def label_hidden_honeypots(df):

    all_assigned_ports = [5000, 8443, 11112, 8080, 2575, 5060, 5555, 161, 2404,
                        10001, 623, 1025, 50100, 22, 23, 20, 21, 42, 69, 81, 135,
                        445, 1433, 1723, 1883, 3306, 27017, 9200, 443, 110, 143,
                        465, 993, 995, 1080, 5432, 5900, 631, 25, 587, 9100, 6379,
                        80]

    honeypot_info = {"Ciscoasa" : [5000, 8443],
                     "Dicompot" : [11112],
                     "Honeyaml" : [8080],
                     "Medpot" : [2575],
                     "SentryPeer" : [5060],
                     "Abdhoney" : [5555],
                     "Conpot" : [161, 2404, 10001, 623, 1025, 50100],
                     "Cowrie" : [22, 23],
                     "Dionaea" : [20, 21, 42, 69, 81, 135, 445, 1433, 1723, 1883, 3306, 27017],
                     "Elasticpot" : [9200],
                     "H0neytr4p" : [443],
                     "Heralding" : [110, 143, 465, 993, 995, 1080, 5432, 5900],
                     "Ipphoney" : [631],
                     "Mailoney" : [25, 587],
                     "Miniprint" : [9100],
                     "Redishoneypot" : [6379],
                     "Tanner or Wordpot" : [80]}


    for honeypot in honeypot_info.keys():
        filtered_df = id_honeypot(df, honeypot, honeypot_info[honeypot])

    # assigns all others to honeytrap since it tracks all other ports
    df.loc[~df['type'].isin(honeypot_info.keys()), 'type'] = 'Honeytrap'

    return filtered_df

'''
  Function: drop_more_internal_traffic
  Description: drops all internal traffic from the data collected from T-pot using
  Elastic.

  Input:
    - df: pandas dataframe
  Output:
    - df: Pandas dataframe with all internal traffic dropped.
'''
def drop_more_internal_traffic(df):
    # Add boolean columns
    src_private = df["src_ip"].apply(is_private_ip)
    dest_private = df["dest_ip"].apply(is_private_ip)

    # Instead of making a copy of the whole DataFrame, filter efficiently
    mask = ~(src_private.values & dest_private.values)
    return mask

'''
  Function: run_everything
  Description: this function functions as the driver for the program. It calls
  all other functions.
'''
def run_everything(file_path):
  print("Reading data...")
  filename = file_path
  df = pd.read_json(filename, lines=True)
  print("Read Successful.")
  last_len = df.shape[0]
  last_width = df.shape[1]
  print()

  print("Normalizing data...")
  df_copy = pd.json_normalize(df.to_dict(orient='records'))
  df_copy.head(40).to_csv("test.csv")
  print("Normalization Successful.")
  cur_len = df_copy.shape[0]
  cur_width = df_copy.shape[1]
  print()

  # drop all internal system traffic
  print("Dropping Internal Traffic...")
  df_copy1 = drop_local_traffic(df_copy)
  cur_len = df_copy1.shape[0]
  cur_width = df_copy1.shape[1]
  print_progress(last_len, last_width, cur_len, cur_width)
  print("Dropping Internal Traffic Successful.")
  print()

  print("Combining Entries...")
  df_copy2 = remove_suricata_duplicates(df_copy1)
  df_copy2 = remove_cowrie_duplicates(df_copy1)
  df_copy2 = remove_P0f_duplicates(df_copy1)

  cur_len = df_copy2.shape[0]
  cur_width = df_copy2.shape[1]
  print_progress(last_len, last_width, cur_len, cur_width)
  #df_copy3 = pd.json_normalize(df_copy2.to_dict(orient='records'))
  print("Combining Entries Successful.")
  print()

  print("Finding Remaining Honeypot Entries...")
  df_copy3 = label_hidden_honeypots(df_copy2)
  cur_len = df_copy3.shape[0]
  cur_width = df_copy3.shape[1]
  print_progress(last_len, last_width, cur_len, cur_width)

  print("Finding Remaining Honeypot Entries Successful.")
  print()

  print("Dropping Sparse Columns...")
  df_copy4 = drop_sparse_columns(df_copy3, 0.5)
  cur_len = df_copy4.shape[0]
  cur_width = df_copy4.shape[1]
  print_progress(last_len, last_width, cur_len, cur_width)
  print("Dropping Sparse Columns Successful.")
  print()
  check_for_duplicates(df_copy4)
  return df_copy4

"""**Data Compilation**
Description: This section compiles and savs only absolutely necessary data for overall analysis and visualization.
"""

'''
  Function: compile_hourly_data
  Description: compiles all the necessary data for the hourly visualizations and
  saves them into .csv files.

  Input:
  - df: Pandas dataframe
  Output:
  - full_hourly_data.csv
  - company_hits.csv
'''
def compile_hourly_data(df):
  # full hourly output
  columns_to_keep = ['@timestamp', 'dest_ip', 'dest_port', 'src_ip', 'src_port', 'type', 'geoip.country_name', 'geoip.city_name']
  hourly_data = df[columns_to_keep]
  hourly_data.to_csv('/content/hourly_data/full_hourly_data.csv')

  # Corperations, num_associated_ips, hits
  total_hits = -1
  num_ips = -1
  companies = df['geoip.as_org'].unique().tolist()
  temp_entry = {}
  company_hits_df = pd.DataFrame(columns=['Org', 'Hits', 'Total_ips'])
  for company in companies:
    if (company != None):
      temp_entry["Org"] = company
      temp_entry["Hits"] = df[df['geoip.as_org'] == company].shape[0]
      temp_entry["Total_ips"] = df[df['geoip.as_org'] == company]['src_ip'].nunique()
      company_hits_df = pd.concat([company_hits_df, pd.DataFrame([temp_entry])])
      temp_entry.clear()

  company_hits_df.to_csv('/content/hourly_data/company_hits.csv')

'''
  Function: compile_hits_data
  Description: compiles all the necessary data for the hits visualizations and
  saves them into .csv files.

  Input:
  - df: Pandas dataframe
  Output:
  - destport_hits.csv
  - honeypot_hits.csv
  - ip_hits.csv
  - company_hits.csv
'''
def compile_hits_data(df):
  # destport hits
  destport_hits_df = pd.read_csv('/content/data_totals/destport_hits.csv')
  if destport_hits_df.empty:
    destport_hits_df = pd.DataFrame(columns=['port', 'hits'])

  ports = df['dest_port'].unique().tolist()
  temp_entry = {}
  for port in ports:
    if (port != None):
      if port in destport_hits_df['port'].values:
        destport_hits_df.loc[destport_hits_df['port'] == port, 'hits'] = new_value = (df[df['dest_port'] == port].shape[0] +
                              destport_hits_df[destport_hits_df['port'] == port]['hits'])
      else:
        temp_entry["port"] = port
        temp_entry["hits"] = df[df['dest_port'] == port].shape[0]
        destport_hits_df = pd.concat([destport_hits_df, pd.DataFrame([temp_entry])])
      temp_entry.clear()
  destport_hits_df.dropna(axis=0, inplace=True)

  destport_hits_df.to_csv('/content/data_totals/destport_hits.csv', index=False)

  # honeypot hits
  honeypot_hits_df = pd.read_csv('/content/data_totals/honeypot_hits.csv')
  if honeypot_hits_df.empty:
    honeypot_hits_df = pd.DataFrame(columns=['honeypot', 'hits'])

  honeypots = df['type'].unique().tolist()
  temp_entry = {}

  for honeypot in honeypots:
    if (honeypot != None):
      if honeypot in honeypot_hits_df["honeypot"].values:
        honeypot_hits_df.loc[honeypot_hits_df['honeypot'] == honeypot, 'hits'] = (df[df['type'] == honeypot].shape[0] +
                                                                              honeypot_hits_df[honeypot_hits_df["honeypot"] == honeypot]["hits"])
      else:
        temp_entry["honeypot"] = honeypot
        temp_entry["hits"] = df[df['type'] == honeypot].shape[0]
        honeypot_hits_df = pd.concat([honeypot_hits_df, pd.DataFrame([temp_entry])])
      temp_entry.clear()

  honeypot_hits_df.to_csv('/content/data_totals/honeypot_hits.csv', index=False)

  # IP Hits
  ip_hits_df = pd.read_csv('/content/data_totals/ip_hits.csv')
  if ip_hits_df.empty:
    ip_hits_df = pd.DataFrame(columns=['ip', 'hits'])
  ips = df['src_ip'].unique().tolist()
  temp_entry = {}
  for ip in ips:
    if (ip != None):
      if ip in ip_hits_df['ip'].values:
        ip_hits_df.loc[ip_hits_df['ip'] == ip, 'hits'] = (df[df['src_ip'] == ip].shape[0] +
                                                      ip_hits_df[ip_hits_df['ip'] == ip]['hits'])
      else:
        temp_entry["ip"] = ip
        temp_entry["hits"] = df[df['src_ip'] == ip].shape[0]
        ip_hits_df = pd.concat([ip_hits_df, pd.DataFrame([temp_entry])])
      temp_entry.clear()

  ip_hits_df.to_csv('/content/data_totals/ip_hits.csv', index=False)

  # company hits
  company_hits_df = pd.read_csv('/content/data_totals/company_hits.csv')
  if company_hits_df.empty:
    company_hits_df = pd.DataFrame(columns=['Org', 'Hits'])

  companies = df['geoip.as_org'].unique().tolist()
  temp_entry = {}
  for company in companies:
    if (company != None):
      if company in company_hits_df['Org'].values:
        company_hits_df.loc[company_hits_df['Org'] == company, 'Hits'] = (df[df['geoip.as_org'] == company].shape[0] +
                                                              company_hits_df[company_hits_df['Org'] == company]['Hits'])
      else:
        temp_entry["Org"] = company
        temp_entry["Hits"] = df[df['geoip.as_org'] == company].shape[0]
        company_hits_df = pd.concat([company_hits_df, pd.DataFrame([temp_entry])])
      temp_entry.clear()

  company_hits_df.to_csv('/content/data_totals/company_hits.csv', index=False)

'''
  Function: save_time_vs_port_data
  Description: compiles all the necessary data for the time vs port visualizations and
  saves them into .csv files.

  Input:
  - df: Pandas dataframe
  Output:
  - time_vs_port.csv
'''
def save_time_vs_port_data(df):
    time_vs_port_df = pd.read_csv('/content/data_totals/time_vs_port.csv')
    if time_vs_port_df.empty:
        time_vs_port_df = pd.DataFrame(columns=['timestamp', 'ports'])

    earliest = df["@timestamp"].min()
    port_list = df['dest_port'].unique().tolist()
    entry = {"timestamp": earliest, "ports": port_list}

    # Wrap entry in a list to create one-row DataFrame
    time_vs_port_df = pd.concat([time_vs_port_df, pd.DataFrame([entry])], ignore_index=True)
    time_vs_port_df.to_csv('/content/data_totals/time_vs_port.csv', index=False)

'''
  Function: reset_csvs
  Description: empties all the .csv files but preserves the columns.
  DO NOT RUN UNLESS NECESSARY, WILL DELETE EVERYTHING
  Input:
  - NONE
  Output:
  - NONE
'''
def reset_csvs():
  pd.DataFrame(columns=['port', 'hits']).to_csv('/content/data_totals/destport_hits.csv', index=False)
  pd.DataFrame(columns=['honeypot', 'hits']).to_csv('/content/data_totals/honeypot_hits.csv', index=False)
  pd.DataFrame(columns=['ip', 'hits']).to_csv('/content/data_totals/ip_hits.csv', index=False)
  pd.DataFrame(columns=['Org', 'Hits']).to_csv('/content/data_totals/company_hits.csv', index=False)
  pd.DataFrame(columns=['timestamp', 'ports']).to_csv('/content/data_totals/time_vs_port.csv', index=False)
reset_csvs()

# compiles the hourly totals
def save_data(df):
  compile_hourly_data(df)
  compile_hits_data(df)
  save_time_vs_port_data(df)

def main():
    file_path = "CHANGE_ME"
    final_df = run_everything(file_path)
    save_data(final_df)
